[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "73f7734dfe6a8a806a396b676f5cecdb44f5eaab"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ba4e5a1ecf165deefd1c64ba0607a87cef79485f842c11ca4c1bff0678df4bee"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25b84a074450235a498db6796b69512d5e2029bb"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b7d6f02283d11e8a06adb75efd867b663d65973f1c1cbb32931e0297b6e0fa59"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eb436498840b00733bbca71323c82b12c2b0a04"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d74397350383a405b3a438e5602816ed863c5d12ea7b24625bbf16977520d6cb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0ddcae4988301fb1b77ce273a4f5f610ab08cf5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a3afe7df233101528206f75136ce5a52a91ead801bfec803937788991904a314"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9409ddb70f44a9a4d5050eedca512c836740cc2"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ff436964e645bc7c491396b6601def72a3d04878f44679688a91266d803988ae"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3cd45e1868f06eca6819879cf2e1ef382cd8d99"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "33200e31fa8d769d08bd52f32e9b00e3b6c248cb41a5c0f77f3cdafbd8ddaee1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e041b45894419477cebe26d35da9e535cfe0248d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e049af1e71cf5233737c7c0b71fddbc9d5a4f88eff369b8eadc7d07c4e1229d3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2748c4140bca5f3b1ddc47c1270d6b04406182c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c65f40bfbc88c87c7b92d23e1ac269d62c559153aa605b0f71ba39b94767edb8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f394b81f6a9ed33aee269f19cd4696b44dcf3aa"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a8a3225f5339ce13164ab261e6a2034a20da443e1a6181665d3e3e3e7205af64"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee6260c191de718e0de8325daab4f68f4539c5f0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "471a0d0e5bee78069142222ceb0f88c919762a59ee155fa64ef91d071ff3af72"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af2b700e4e20e4d8da5b419eeecef5d4f250ce7b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d549c309571c3651988689374e31fb843d45bee62caed4f4f4e95929d3c7882c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17e43b24f65e7284893dea1915232abcd19341d4"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f26aa0ef3912b889fa6baf2f2fc3bb6b6136b731ba0aed3c77fc43503f2d0d17"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85d6d3368950b21ed3b7fefa95c9d913b2bdcbf2"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3074f7c43ecc4c41f5cabb6d34fdd1080b7296b2a0c44c7990608a733b64909d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd9d4b9452e0c0690d44b24b40967eb8658b3711"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8a7944d298df0f76cd663ad2c7c9f18d8912b6ae68d5162538bcc21216789fa0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cf9e66df65ddfd49206b383756b1eb8fdca92c6"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0c7bd4650b35364c73cafcf00c096b089e44dd192f7203f6eb7d85704a0e6dfe"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a82c8ec155aae3f31b1a1c6fb6d1729df41bd06"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f8de45337b7df17eb333043a16666548a3e59ce927193855fc791adde5a2a89a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1c1088e405d9e44268ec1598e666b079c342dda"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "00f5bc29efb7335ef484b52c739c1e5e090b0748bef176ee4700628bccb2c251"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b227c8722e69a6dbd26aa49e5c3806ef242c2697"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "be93703474d1c7211f5325e90a92ccbc6184bfb3231bb7406b7ffceb1ad71423"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "507f4d6e45b599f13917439bb94bc055911c6119"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a245e54d0a089934e4e9c11448763597d337aaeb09d92cbc29e039a0fe1c38b6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "23e971e97bfb3b525e3105c19cbc59669147a133"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "467509a07c20928657095f5b83c37ab0bf9dad1fc3eefc45dfb1949c451e1e06"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0bbab20bed623a877dc0ffc8f450ca62090310f3"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4b0407e57c4db338f2a62179f0b5284216b873190faa5db6e2f7bc8f21b95c43"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a380d729817c334f64469d603050d9bdd1bec1a"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "05e6f748b4c12d1f079a19bb41e2f81985f37309d9b4fbe9c7131213dd9b5092"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ca01b9194b4a9c8af1c868b3a8325240cd6f6d0"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "43a2c442adc95d20b90af8e131fbcfbc26fdbd9cbcf014a4c39f2b64d4447705"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77246c6b3038c7bab3caf4878fc99d8ddd5667ac"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0b7b03cb60f92a831f7c1fda32495bdff88f053c504b30fc810ac7c8a0bcba46"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "fbdf7937112d5e29d9764b6dcbf1a1a85f83f239"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e153133d569c5325c5273c832bcd4e787c8522ae2f2538c5bb6d32c5bfb32191"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4567d4c2658d0ed893dfb4c66a9f4c858602a6a"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d8a0d76f474600940bab676e882f07a8323364154d52b6585b9540f5802796c6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2cb837a8a79ddaee34fdbfd48c0e1b096af42e4"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "91a757a5bf2cc9d1f50a955ce9e0878da7bd4d71b3991926fe0e8520a4820b33"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+0/SPIRV_LLVM_Translator.v15.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
