[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01c67df7b000c570675f6753e8c31f66164e338e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bc495b207a2d5e8a19b0edf5ce1c241f2131cf77b58f5000df98596d612d9c1f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f0780826bc0dd01fa0330d16735b25f74e70f1d"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d93e5bd61fca3850905f301e7792ff5ab2d51860ffbafc2b9cbf0e970cdaeb45"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f87e4a4bd995ff1fdef87a4ee8b0a1aaf0c0ede"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a55c2fd655e23f94860408e0bab10451c598f0861ba8e2dfb0a3bf464a0ae8ca"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e95ed82a2b9dfd978f622d117cba1499401c896f"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a1c6f5f3fbb86a6a9179b1f73b9e8294e6dd0d5b7191ff1d22830a9d05cd9910"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8281ab5ee020e24d67708fda5fdd76e573eddc9"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "fbf19b9702eb284390179a34778362afdb66dca12e515415d00feb76d028daac"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa0853fc8bfc20e393b26c6570a775d065772331"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b8431051a243a471d26e3c00ef715130d973ec74770ed0a436e24f6ce940b0a3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5aedd6e416f362e251243c118dc7a5e9494f71d1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1af669fdf44ea3628f233c3b6ecc628a5b3e72f11820d1559140b97bb28294e0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "016f69255a3801537b52001133365fbc6d775b12"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0a8b06a3e7c03054d97fcd1094e6811f9ea10e04d819b6e09e08d4dbce3e42b3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc673031fd6300566c32b456476ffcd80d66b9d2"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "2259b9eceb1a8f85849e1c9450821a1aa3e0c9c9a96e735d616e303da83d924f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fac0b2e1dbc66f8a94b5c22763d9ffe9c62998cb"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3b08907b77cd7dbd0f6d7550915bf478dbe2de04abe437a9026b2a567a0378dd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "132582e2dc30e360204d7b52de93149dbbda93cd"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "2e26c92587e76ce779a46fff9ad260360849c65238b6ed4d4868dd04d00078f7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6c375ad4afd1c334c9eebcb75d98390b47ea1ce"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bba8ecbabe0d7c6f290726b54c154841f3a746877a6030ba50a52b4705d78be9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eac388b48faba312484116cb25edb651fce6d485"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1e8579054c5b50de0aa66eac075e22b1dbc5e99539eec8667021e13085da8dcf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "887580943f154d6801c518e8ca91130f4aa05ff0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d0d6ac20f28213aa573fbb40ff91e94a71289ae2b61bddf3daf3dfb2484350d5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6fa95a0e53bc11d93427fcb2acc36aa2ced32f0"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7f31dd0c4240d2aacf660fabc8d12664eafea17ccf40ebc6ea8d9a8d94ed41e8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcf6f095e3d830f6ef479c7f960b53a0895b1bc3"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c297896d8c3aed1b73cddc4fa53889cf266aab2e0dbc1458494e5dd532cea20a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27793666733eae6f21130e16efcd7e4d3c9947aa"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e925ca0134b1013a067652db4fed7999bfd24904de9e78670475ede5210bdd62"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde196daff3891de85fb6ebf266c0a348f5903d9"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "25a8688b929d6848c2641ef0cd5b823b4f9aece48d1e56bb7ef5b9c98c7fb7c7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e86ca4d9fa6390a6764e8aea719b785fc0551ea3"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f8a09b27060e68eee2f9f5b5ace4f50f6a47b4a5b8082763e8e1ab44aa5507f7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f991852b458258f15048c4171eae917ecccc965"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "27eac63f743fdee4fc7b534614f537f6c48a5f6eec2b1c7af17723149d23c2c2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bc8726cb35b21882d2819ad4830c6056c576368"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4c43e05897f64fc35a598203d4f4aad67e2c5ec36f3074946bc0aed142ef624e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d28b03d19bc04521c55ca169785facd6426572a5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bd1fd87214a59c56d89d56d0fdc725bc94d97b1e64ce61d766b7225ced335121"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30cc8da7c6e0eea9be0a5b5f9e8e76798ec7c97a"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a80ac92565721a73818b35480d67d3e3ffbfef0eee8acea49ea0f45eb408b185"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "203463845d075f631d2fe85f5704554f3420da2f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c628d61c91d18f322dae8e2cffe7bf131773175ab4a7408639fc464d18fd39ac"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afabbe1e2a41bb1ccde16d0075076cf3f2d94eaa"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1eb73bc6317c6cbb59879114dbddbce3d1f1461796562ffcbef37be3acea4c5d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7896e1a94ad594dcb2a34d582e82d9f471cf29f"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "cafbe419fd52ba0c19296e5991991e4a235162314b1e2212db737db76cc09d68"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v9.0.0+1/SPIRV_LLVM_Translator.v9.0.0.i686-linux-musl-cxx03.tar.gz"
