[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "a3832b6331d4adda99364debc3c51115e1713019"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "41d41651e9a4bcf30001cea44962a4b18a30911ed91b09988a0e31c96b0b526a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3426062c861e6e589cda896ecae874a4b96c6e42"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6062a048946d426a6ab9bf96203d216f047a1e816b366d04259ad26657d70c12"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c0e0930f2e5c1dd976d347db1d2bc39d120568d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "886c1d78ab0259503493a2ccd797f08c9b9bd19759cd3e764372dbce730376ca"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24546c7166a277a5d64f3eee3e5e9ffe2fee0e03"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "36ca58a1e3f3fe8447de0cb670043b815d275f0d397d5a8a28ccdc1d26a2058f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a258c020172a55348b95f72d1947335a824172bd"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3b63fa7cae6004d7b2943bb83383616b6b7d19fa977fdb04cb85cb384fde6126"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8f352d949dcf07d7b5639eb26692cee2759bebb"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1e0ad2a460f0382fbb3d94c536af7206c9dade4da180a2e528d7af6e9abcb521"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f7f7825bb8b9024c22934cc4352eac747a1e2d0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4351455d77e361f08fee35fbfd37ef3cff32ab99fafc0b6f15670c9787683da0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ee8a2375d4b237b6c7b938690abb26d86e2d2f7"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "073d90a85f6d600a85da12b9d931f31e814d4a7d3d9923084d7d9e7e0e17d772"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "facbe0907e54caa038ea46fa4e1c2f14c937044d"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "edac59f205b9df99c355bea9c7fc0061cec31682e969b6f34c547369ea3fd611"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4506b2ca5e3f6125b039eb885372305fd8be8f7"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "08cb7eb5f1d4126ca2240007949a387ec63493e47a1f8645ec6efa35f2093318"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbeb40523fff5d7dbde3fb2ea450c2ff8c23c28d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a5496520d592fc872a02b443e9a266e3da4e6a9280124ba9a0f7ded9d358a59f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aa575336551dade18ee26f22ebca0653c3494e0"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "73b6340282020205f7d961a4e1368b7d07b03411b8c9e31d0d83b3b01a93cac1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67f9a885156b716494500793f68f4691f48dad49"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0a10a13c5406e3eea902bd09d4301f47ae0ff9021da98a5ba9c8d57485ceb984"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2376eba5842aef33568a08ced42a3a0707811c6e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "26cb49c2a72931e612b5f2d47026d0fd1d65ba81d5cacd4f0fe6791e199ec0a7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6348076b9565e4d230572259086bd47b5c028825"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "784552cd0d60a4a9a892ae56a72f05b60f9083999cb7194ed3897d414498a32b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "466df01f10b221bfe908cfccedd171a4dd0836a6"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a865832007199d6e053dfc80814aa868c9c6730529e542658c9b618de84d7bdb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "caca7e6c958fee654a90b17a7fae8eddb96e39b7"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4aa2d44ebb9878cb8d46bb86781e51c2eb92acb0a07333bd5484615e1821f276"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c35a2de142c964dccf2aa57bc126cbd4f039cfa7"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7f5bd6ec2a687d8612ebb04b08582ac9990d7160582ab484185c34de4c917e1f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d53f1e261a61362b22052a8e736bf354f06c731"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "eb3969894843b08441fcc142ce5cc2e21beb8d758b42d7be7521ded054a2e05e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5dabee14ddfdf115cea234c251944b8c3c5b39c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "815fd098148dc473c4009740d92d35bb39519fd62e81aeb25c0cf64655c6cfe7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "708263542c0e452989bbfb109eeb73fd8bb79227"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f495e2eb8535f6eb4dd146306ac4e511462c31e6b1e4d65ee8b0a2d1b3ba2dd9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "1407a9c883902d9de1d73046087dba32b9e828e5"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "76b1eff5f6ded92f8728c6dfb15f9aa4fa871221bf6f909a5f0bc5c3ff2a6f9f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65b183f1f7fc94db01c4d1bc50f882df13ceade5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4ccf74e212c2631e197ad03dcf73598fd03f6d0843b58afa5e1c6b625dd5b4b8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e1e398a60eeddfd7095472ac4dd8c5c1c5ea1e6"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b96d9b5adf2af08fd1f14e1a07b91df15e0216b546269d67243dfc89af545e50"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b99f39198b6403db28160abd94e3ca462884f5af"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1ad6100779153f74b440cc5361cd7892c9679879b0f7171f28e01e184ac84bb2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9bd90d73bbda814636e59c76676aa9806cd88df"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "09eeb0eadcd2341b1dc533cbfadc8f9709c261fee1aa98078ce55e6aaa144b3e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "9e958d52d429849594125a32de69d9532c56eb05"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9ea03ce0b2e57ec8b740c5ff4ad4fa6925c9a5c7622bfa8c9180e1a08a2c44a2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b46673bab90aca5f485e51e800fb26a22d67ce5"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "286f0ec19d6f2c657d0a8547125e5ca387fa3ba75db6c615faaddb2d1be6a8f6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d7d8c757c0d09297d8d1f511a0293c54c70efb6"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b6ba20c38e25309e66178de445ae4b0224c4a1f98a7e67bbd9a79930ccc01007"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v12.0.0+1/SPIRV_LLVM_Translator.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
