[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99b2999cd0453d7ee657591ae17bb3ae2c0ceea2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a2d29e4c396f5c54fc00a7f837ba4df9296e97d6c154b085f4a74e6f6ba7fd81"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7270ab58acd49bf8d85b7bc10b443609cd1bb69"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "02bf86609f85b32e9f92d725fba0dec3c10b023693893b49f8a4f2c52cc7425b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d96e1c3e782c3548430ef9eac6ed8da0814b3b14"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "2462500497325b37d521a7ff037fb4983206a243c532bcd532967651ce56ca47"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02ec49002fa8da411178117e1c8a5909410a8c29"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "32d253dbec8791b4403cbbeb3d534fe9f6fd1f657ad54d06bfd107d48e502d34"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8982e3462bdf61888b2461b83459687135dfd567"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b5829968fbd7e04128a53b5f77450908ce4f661ab2cad9da8431b2fe74c42f04"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7a00ccc346f7aa539e7c2c6cba4363af8f7ecfc"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "114753887ffc54699752eeddcaa7e0267413cfe17e07b34265b54ffcad45eaf8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "170b73173095e621c2134949b8c8102002b5849d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7d06ae2791d0fadab3ba6d63ff880b7e2ed3defc147918452fcce2b96578fc77"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1ce5143c8140a3159e63fd6b8511b9f5381e2ba"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c22dc06f6848f729e300a08af295ae9d7fd12ca2682bf9c1c9b1d08634c35acc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b087c7567b7fd9db877ce550b6df3537c429f17c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5487aa8343be189ba762b973b78e1fedb99fdd8adbfb99d43157078d5a73e766"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b83ae6baa2fb9a7f4aabca25f6f32815aab45d6e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "54c4c51319c991f0ee8109ac4c885c0bc5ad63ca29c87f6b95bf1230f11f6978"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3609a4aecbc82f2ba4f5263d6ba3c69cdb5bb025"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "57ad23aa6436c77eec3765a5a78868c91906abba241374693b7749b342389043"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "d47c53c9d9229d878c429ba7288bb15ac7ec0ecc"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0323495797b93c90d624cac61530403b740e676cf92b087047a0f54799f2ec6f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "0ea8b0b96ac417acd12712870bca1f1ed0dd5a7c"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f7bbbdc4ff2439c4c8ffe4898d1dcb62e6fe1c667ef864e858bbbd71dd75cd8f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "154613aab7422e303b2167f307f7dfbc25b6d391"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ff7e1897d01ef6c8e1c3233116591d6ab7ba925d56b1b78b451f6dad6ce89e28"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "ea9efddf41b8a8f825bdb57177a0a32ca4040828"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "cbda9fe6a172076b0c989d4d01f5314d876728469c89c566331bb60687947fc3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0af58539cf75d0f866b683ba907df3df8da89f8c"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "329deb7b3fd9b4036356beb193b01e9c2fec919a1cc6fdf88a3e4da97191dc28"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2edf0f38ccb4f678b87a7d7d7705d069479d71d"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e72f9a07b06d7a7a7dd3998569f6fa294bef14b504a2dd0d5c0a76ea2f9be832"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v21.1.1+0/SPIRV_LLVM_Translator.v21.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
