[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7952159872cc8db8cef7d5889580d3b415bb6d57"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "08ef51073702f1c921a74fd63765286cc9e119df45627f099f81671422d33aa2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64740e21a0d2f4f10ff3dfba9e639e02bf8b85a2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3650d2d56f6d895fdd10b92ff9694f31db3a320e5d6ff26007b6e5c2da62d414"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cfb4227ccebcf1fed88e3d2e2d0eab77c44717d"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "dd22e2442dc0ba1132874a60860447444465c25d0b7b59f3d9cecd296018bda9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de4cc84dfe7d30618f68f3e512aeb24238e7032b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "26966dd8ed2d7a41525ecf2eadccfe738a117807157b49e2291c7d915cf1d0f8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ab288b849612b651a236391864f6f9e68a9efd1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e61c9c0d2f850c508f5c847697f40b2166af8d3ab32a72b80b4ae715d0531559"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "620056b6cd43ca7a5669c395f46fbc35c5000ba8"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "20e37bcc7d0d1bc7b3fc9f26b55478d88e7348b00f5fa026e1daac0b8290a8ba"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54bffb7f23d2db7fa5c43bffcab743a8274ce86b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6172604d7f53096d9fe2a93b45670aa4abd498b3e5b309abbb71f6c18fd4e73b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b59938b97de1591874e3dccfc86c809ba5b2ea5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ba0c2faec8e6ff561b1766d1be0d54f7c2f3b97693973f7f23e71a8f6755c9de"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b528dbb37bd59c0d52adaf997c72137e9f99b03"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "30de636d1970ab61f729e247fe045750f828d78f90695dbd53f35a745cbb3007"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "defa22903d8689ee87b80effbb276fffda4fb314"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "77950de51f9b4586964959b7fcec8ce99bd911cfd6310eae8782decc9dac7347"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32fb1caef7d89ee67fefc35b7c5df09a0ef9b671"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8c2fb29c219a47efccfe23c0c2d4243911de0e24ccf6ad7492e0aa69a93a91e2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "17df353a7e26dc93cd22917cc4f4a9434398a266"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d1303761cd24f48986fe5ba53fd35da5cda9befe2bc7f46dfc2fa1769c299edf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "78367ed7b2735a9905fdcabd32ac05c27709b471"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7c51427e290329f3d3a7ca707dd50e2802788be2dc92740057f7ead526219496"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "186c2e5f263dc6dfcd53caa63d67862387ea3430"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d49a3312e5a74176584b7f5c402ca5fdc2d9dddd9302c3051e92ad597a11e4b1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "4a9f1c11d253481e30cc95db319af51c657e7107"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9199554a05e7a5147150ce9140040b6d6a427f79167e4aa6198cbab47d2c68d9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5591a5ac386c55d67866c9eb87e75cc016a03c71"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a57d0a4b8d3c0ca4fb624f5588a77c7e4c6cfd847c0754b61f5f0417193422c7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56b815ea24fdfba4d23bb14d540594de27485f96"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1d9b9bd95bbafa8b759c9eb5547865f97c9ab2ff7242571047785d7c6d5ccd0f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v22.1.4+1/SPIRV_LLVM_Translator.v22.1.4.x86_64-w64-mingw32-cxx11.tar.gz"
