[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fef99f1dd8a7cb11cbed4712e489174dadb1307"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e14acae8f328973cb7740d981cb1c3017ba8cd46bb722c1e9160f2d41a636ba2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab571862ac97c8c398aff77008c073c0508554a0"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "845b10d42b61efc29bb45f995e26287a0f900910392358c99238ff19e6a61d23"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00417f78eca1eb69b317d8cc0a5adcaae500b2f8"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "071536755d40166392874111c70fac298990208887ab2300fd85380258e124c7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "913beb6620c7ca7e712192f03ca144052e4d842b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a01c69e59d5ed5b2d49033857ca0094930a4e0d1da71a24869539e1364a28163"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a2f9020d7a8b5f028437365dc2a770cc861f159"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "40ff41ce7e554e69904d8323e0395b1ba99550bdfbdad0f8c7bf660c20fd9403"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "808bbe069e02b1c5d2cc7919997a90e57181e25f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5f4e154ebaf8b1da81fc3b7b128f7bb742a0a02a57111f1e95a98b6955e9bacf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31146b56a6be33d6b9c6f94b6842e57ce42a6905"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9a2477d25dbd9f75727d56cfa119129597e51d2072dbd62bde99beb20a86e854"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "919d9e66ce4de876122a88a441b5d525e6401cf0"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a15684d69d310573aa1dfac9e7ce96d5eb75ad76eb84f0c787bdfc9d80d36024"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97c1b26681e7057819015cb09c0ad33eedd008f4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8492d2d2e993ce8c41e8315c0771bb8ec5fbf88ba8dd79767ebde483a9758a9b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1fa48292cc5bee04fa1bd6d6738cd0b3fc5bad1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b72a37ff29d6efcb9820f3cb04a854c0f6c6585bf1547e06f7d5449a57aa90d1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6ecff023f82617f004b28d6f3ed488dca2dd738"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f8513bff3ad4064348ed392c20f32e17481b27924272cc97f0f5ecb167ba74ce"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "995cfac58d67d6edb99a2539cf8935c7f74204b4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "070c1b2c56853b5da6482ba1fd62b24134c05c96b46bb90426fab3449b9324b3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "580179bee2b332fad1c3eeb4812e7e1655303f03"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9138334334b74b871db7b9727cc9a2a39aa3415869c1ce67e8836e72401c6de2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "260913807b4bef72d2bdcb13d31520d736f6a2dc"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "675eebe8dbc75dd23b8620fa773ab75f2abf75a1d2b16b82b7fc39e56717b7c8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e91258c365f5752e23dbc676ffbb24956bfbe29"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "eb1eba865c6b5ad1396639811a2b717d4a688740ab8fe4144c84a99cb36fc038"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7788fedd1134261fcb9a9404f5d5bfce6b154432"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ca6547b156f003ae28dbc04ddc27df4e8a3af9e71d4509df36e607e5ea69c65b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67ad980ee895930e96e49c6a8a5e5037b3f9c1b5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bf89e6f4fc94eb87a687e83cc0f18746d3501e22b0824b9487df897ee0710d83"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd8c24aaa0c218491d7477f58f839af0a30be9b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "079639cf9625773317f1e67ae9fe1500e45afe0b90cb85e64c91c3ac7caee79a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fd5208c35b3d957a98664ab2b7098bac5711153"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ba614dda47c8139e84d0ee9c51aabdfedf9a983a24754fc94f6c53aea46b68b4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ebcf8094706f5fcfc0bc517a01796ec49b856c3"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e4ab41fbecfe551e79ba9b90f7caa7683db069cab96c4cfe9129929d2df1508c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d672aa017bb7680210efdb239702555ba732e29"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1ea32d9e09bfb7fbc4c187ed06cbbfcb5092f54d67202bff0deceb56e7ad1e11"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2eb41b8eaf58bbcad911826221f9f895bd8183ee"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4ec81a01c28f56f5bb5622a19e4555efbefcb204af2c7659c618e49d9faadc39"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v8.0.0+0/SPIRV_LLVM_Translator.v8.0.0.i686-linux-musl-cxx03.tar.gz"
