[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "836cc8d7093d0b1938ee186803ab169f0853a032"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "737839771c639b9a6c04e9f4645d5bc4fdb5518365b3ba0f3986a8eb1387850c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7c4678154d40c4632e99333269f877c1db753c5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0e8334dc49b3df9bf2766e57d2596313c40d77e2c2c3eed99c204f8d77e3132d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43eea3a492f257008d0978e6ab1f72c4ad914cbf"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ed003958caa08cc070f902eb355eee38542ba094b0dcf1e99c20a1710cefdc2e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e98077dd4b8c7766b19401c65ffba84028f838b5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b9c39bba21eee84676d12d9ebc7926fd39e89a30779ba23413ccd4d411c780a1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "616194b75ca9a3b5928e819f316a4f40d334b22c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "eee2005e19f842188c7a4da703270db632a195a0a6ace3381631b733557c7ee7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19a9a6ec12ea9a8a98eff04b6da1b83e51bac3f7"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "00365804b35b415bc0f82d8cc0c8f0dc82d6da504ba4d1c11bef930dca24d8f9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "329f8f34b2b96eb54a3141839ab5c311fbf047fe"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5ae34379c630e4886a2751edcef1cbdd04dce98aa1e58cdfbeced6567dd5772e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d10bb3b1f1584ebd703ea38c1296a10593a0b958"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "cb33a2fe6944b1e0b577fc3b3076e76d060a5e2e0cff7539047719934d3c1fe6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ade6615a3ddf1189eac276bc15b5c59a5976bf7"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3d40e7d5de17d38074c5384184e4e6da8d33f5bb4328195ec5186d4b519b108b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99f9f87b204045a45bfe21eeb5a859cbc70d7ed4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f0c974f6d6ca4cdaf1a1a9a06981f13d9ca1e80e228d75d7d7ef76b05f5de33c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64e854a1a039cb9e27ff7545b36da737be9c735e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "abbbb651d2240c95cbff11c12b2aa2be6aee017a5c46f3dfa2ef8522f34131dd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde64b9a14af4671af4acd7a8055e9b00dabf640"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4be39e5a509c39b522957c3e95e22c57e52a8065c7e3b101750bd123e287b93d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fdd985467a0914f490ef8bfe4589731d4f13233"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "24ee2a00aed32a4f5e6dc19cbd67878d28fa203417b91b61c6a7bcb752d10b5f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e48c04f2e8e0a26f32d0117541e4bb61551d8743"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4a7d1c26de0c73d93b6e2398b68ecd6c2e8cd22b79bbd9e707f04793372bc59e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d833593b4d3da3d8bbb430c2ce55a9ae29ca5e7"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "aa7cdaf2cd8cc4ff1c4ae5721d38cd8d7af8bdf3928dc6c1252501710cf6aa2b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f30bfd6f390a96c6a7f43ddb7f5dab64dffe37a"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "25de450a0684752ca456479f4136cb9ebb6bbf7d521623e346e5b4a26a09dd1e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2994e5d7c4d4e57822de9c29e5c917d89015987c"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5df48f5dc2ed1fc72e6e82052fdf855f25f93fdf288bba8016762b7c878ff9fe"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f548e75612ce2222cf178173f7c8841185b5d3cc"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "05d53d98a1f87d51f2a4cc85591de35c61b4a4bf309dcbf4eb18e065a9be216b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfedf8ad7bc8c4c93318ef67571cdc7b06ca723e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "66c5447131635ac7de55dfebc8f8902404a13f3938fd588091e504ee5c1d570c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "a9065ef13ade6a5dc7963fc69f4570304bb4cf95"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6c1e08ba04b938736b6cc7fb823488a72a68dd1bac454317fa5ef60f335305e7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98860193c9bf84d84dd864db0c87bee7cfb96ffc"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5d8d0f6967bc0d41950d35299db5baa577d634353814a1f1159eb85a1290a62f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df76cf27c0190e84fcef415138b62e2928f6f816"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "41a5e9139fef807056a361b25f6e9e8c05062840a011061642af848c8184e221"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "002d4f8bdb8a04463474bebc315828d66b36d9fe"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0272ee628bcb80c773ce2ad056720de92753766815f195593ad3b2cf2c61d139"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4017f30c7df4f86041e67c9359f308be4315dffa"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9aea8b80570bcd58ac24c30910d178f4f8abbce4a637c514f1b4fef33a7dd60c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "633da0076743e83ec1326f8f97a418f6b2a7c66f"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "be296c729ce8906bbae17a0b00a5275791e051bc2e6d2f54e6700d603b34311d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10866d645374664aa2a858045b7537d23da5397f"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a63e84156deb8187abd9240a3a23001dbf456b31ce90e048e0f0e576ed68c0f8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6db285cc8206d7444f32052a2c0c6497fef467af"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bff2a7385454103b20e0422be6f6fbe42ad3a68bf1d11d19806e982695621be3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v18.0.0+0/SPIRV_LLVM_Translator.v18.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
