[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "461480487e5a77c588a054357b455ea9604a5553"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bf82029b8aeca851131daa278a8e04ec5088a9418e4e6c9367c1695a6e4e9621"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b63447ff0a619b86e72eabf70e8d855dd2658a59"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "272ba688bd9b82dd1a1dcd4e6e1f389cc87bdfb1b6c7b18c0510c65e787b195c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725d94ccbd3e5e3bf2f84b10f45cdc33dfb0ac77"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a7cfda6ef6b02da8d59f69f90379ae1a651183ac8d08fb5d8455efb337c82daa"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58d56cdb447865feb260e7bfa7dd865548af6df2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "2da3cc6e93b29dc78a05ae42453f3746aefe0727c7a95c7daffe7c37435daaa1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc2b9df5c8077314f5867f64a152da3360a543f1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "cc9d76046bc9d82d4425e1e7ddb1df0a6612cde4872d6fedbd3239776954b92d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "409bbbe6747d5e84d2e368b3f3912e41ea548018"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a630b57d19864d5040b40aa0c88e5bd9b8eac2cff57a77a7ea5cd01e6daa13a5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "138f1746d987b2553a92a1eda36c070c61e4e31b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "29e3b43abe1536ee32bac162add39d79987b49e712d1259d8e53fe6ab4d91879"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ada626d65b75c07a5ac360df84d94af7b47f05d6"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5c22c19aa15ba201bcb9ebf877b7cd35e9500c13665c3d5c1958993cbb0824fb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b43325344c8da9995e67dfc9302536ddb6dc1dd"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f49c99bfd7c368612845e75e6687cf61cb740f737c5097ae619d3ce92a3e6cdd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bcf193873b4ef21634ba77eb3811602b5cdeb41"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8c96a6de7a0e9af7ba0c5dadb5c0911d593f8d65527359bed13bf88506644ab0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac74aab25cef2b51b42a0c7682d2492d620b8d03"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6d41b9c45243db3fd2a46975495734ff3861c28e89bb6a37daa72cc78934b281"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "5b61c838202e9dc42e3dd7b85b4b24cee913e321"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "93c3710b00ee97beda50ce70d297f5e30cabe785bcc043537e50cdc556dd3769"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "0c63a611b4c4ad46391198fcee56c9cc56206ba6"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c20f32110157ec78d0a199e4c6a45270d97d21b537ab049489b4b9f1c0673db8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "e42549fc6d27fc88719bf6e0770fb2eb7e85fec2"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "64fa2b98eea6a38ad203962f5d71528aa0c510fb5c4b4523ba157ec942027f74"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "eb05fa86dd98d582feee3bd4a2c1a87984192ae5"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6b011728b7c7522c14848fd9335c10234c1c6443091a41633dffdee937c76f5f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cd1c41e2c4a153990e93a8c21b069329c9d0bae"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "928c46da0098846d70e0fc0fcbf02c2c6573dea5ea63f008cb96bbd57e070706"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dfc7d6f086c5831d5202de3d4a817acf65761f6"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "beb6ce434b41da082469964cd2561236e8d8cfb8cb427225e436bfc8e0225647"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+1/SPIRV_LLVM_Translator.v23.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
