[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "8095b305f0ae7969600003bfd699af9179130dbc"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "dd5def788273d8468906ce9106975d0751503b11b052154731b5fcfa81838f11"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7495f2d237e5feefc03eaa3d9ace437e60d0c674"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8c99717923ee7d6063156aca5e8a967714161c816ff0eaa2d417db607ab3f615"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bf7f1ce25ecc988adf0770e10ea91cae1584985"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d811f90ae5705444de7426bb37b899e0732d827ca809b60f5342aaeed81e6ed7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4724f59ccf144de8becd542ba9dbbc9cf129772b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0c54b4140034f51ca980e2962b150f8fae0607ab715dfe985074d99c2c1e8c8b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f46b0fd3449ee662c059baa0b3fe050bf8644e4d"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e883faa3500daa53fd2ac96d0568db5e066437a0ed6c760a885a94a44c667dfc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afc160c24da98aa9e666ac2db3298854fdd0185c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1417ad76a8d1f1621cac368f2323b5b6b0d3475e37409b9172232c37e50c7129"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f76872ad7a47d3797cff63f0edaac11352894ce"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "74b390885d4687bc088a452cdaff36d1a24096652441aae5a292e41913a25f20"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97e87619e8a65c9038f8d4a4c39e83373eda291e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "24a1e98c9e434c61ba197f0514576450258a38d347afffdfedcf5a8c5d190196"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1db74d44b628ce3c27f8e901c1544c5e415b274b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "28c5a0c00160a65802b5aec3498e43df6403a9adcb8a2d723eef6e1b4a91b059"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c1dec95e16aef4c4e2995ab9ba41775e45ebce6"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "99f373494fef261df170b2b778d2bdbf5525c675c831ffbb2ca8ca272da2a979"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8abb0fe1afe34c1e681e3b76600d7ed95ea941d0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8c5af2d7bed88c6fbe4b7675f1afe21e5d0f1702ea0b345523e297e609dcdb5e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37880d5ad23a9b89e28348d291bc8c985dc4a7aa"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "889e1a0721910d74a149cbac8c28a8f4188fec882f34b1e5036d760db4e5c45c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17aff446f81ba69128402bf32424f1bd44f4f229"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7c4be9af1f186d0cdec934b430479224919c37c260ec9f76b96d827115246bff"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ca28d213ec58fffd728ed0a34528d4c24603cdf"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7b01653f39db574eea96767d963c2060e0ab1871cbb67995855fb4804bd64cdc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f9c93bec9bb8d12b19c4bdaaa2c5c184c4bcd4b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ec20aa3a8ba1ad25766bd764c44774f9b4d6562e22a45abf799260f54f820399"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a433a124818f040ae898cf62290136792822a74e"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "64debe67ddf9acb79c6b40ce9af45cfee775a90e755a816a265cb0db79d6cf9e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9ecd17a9f26fb2558c033265e9409526e721f08"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0495d5f8179e60d8e68c09baad1c565a00cad0cd1c280c762354ddbeab2b4139"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7c905011a467f92785acbd650299bfbb3514392"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b1c531aedb239342cec015180d3f0ab5c8adc10e73b7103a6b680a00ca18866c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36e3b023203b53da19a8a68e68bba123fd4f0133"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4e29dab2fbc2bd5f67c26fc579bf78efcf2c0c1ff80d70b3dff3a287a2a46562"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "dbbcf34449bb011e269880fa898757fe16086129"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "908eb36123a2cd6e034c0010450e595b763113b018d2982cda4c732edd6b165e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05798edc05d2da384fa417eb49417b8c18618f77"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f3d6f6a90fb58d8ef1a3eae7767660028d93108fc68ff4f281858cb08ce627cc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "995f0e042152fae256d3e2e92236cdbbbdc30a3c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9f2bf7c70ac12c0f8896afa83fb909d587557522ae9b9e4ca13298da79285987"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84f1df4041745071f36690aa2dc71f8d41cffdba"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "8d291bf86522a965db7ca6f9463299e28cf845244b2df599c6de2242262f87da"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03269adc888dee81a62d612d3b243662f4af810c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bdb2ef39133a14f481be7beb4085563b47aa7432bd402e5639ce29ce236387b0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "352537ff703ead9f81815972dfd905cb30d470f0"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "36cee63c449445dac3eaf4ea6055de31c54afe33bccc7a13bfc402cbfe39598a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c65fe58468c54e7a819b4746f4092236764583ae"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1ba0f0adf1cbfbe5102c1781c63db886e77842714dfb1b40d0aa5a5d5b81f772"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15507c62f9933112611ceff55e0f563b50afe622"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4a458190e2642de24a074009efa9c21235f12a07bcc451d21b8257505dabf189"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v16.0.0+1/SPIRV_LLVM_Translator.v16.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
