[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "68d71de976435e4d1ade6eb6eda43476293e234e"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "9b630a833bc0dc74ae912a59aafa21e64f2ba21af1852ab870806d49b18e7f5f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c958de69ff7dbeea93feb1558aeeba4f8fef7a3c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f96d7cb5586320a510c4f7759022a42aa3f1e638758e448b1d601c5295538b28"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d18004366e7096a3062bca858e61f597b609727"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "2232b30b44a59ed07b9f757d0552deb6ddc9dd70fa25cda3ecd98ad27bb681fb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a11c46b84010572e8f9208c6c77dec6df5f6a950"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c578065e76bbe71ec16a80186bfb639bfb73d21f89bfc1d4f91a375b6be179f1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6095b040c5bde0c3f14cb3d48a7390a8d517a4a3"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6a296a8d5dbed3471b928337f63f082b468f17dd295ae0aa5e7c4c704adc975c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66abb7279c7cee92fa76e5d003f9c3f81ebf91ae"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4c540b56f9b6ab69a56a57c9b13c7023faf97ea6142ed73f4037dac35a40c086"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41a4dfbe01f69c3808704d73fbb48ced43908a41"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "07039f7f96fb39e304532fa9afc97246902a3765889ca1ce1bdb9f845996a43a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b22c200b5f31eb0f562debbfd2711fbba81f0061"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "afed754d5a72b78216b338c08379de456ead0e30cbb1989828b6e608555ef4a5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec1c4dade58c28fa0b341561024f8bd1078f0e8e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b7bb937fc53fe5e3c20b27bf7bdd398eea003889d7ba31c7941290a616ff9153"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f57857108c6ef8decbbbc76839b4ea05ccea774"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7de71db3925fd161759c5c0de8a7d9d209b2485402dfece10e26c55eb8d16800"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6e3ae851faf999285ffc1d39dfa96c3d9177042"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b1a035a283976dd2a1ff1edae9d6f503a5ae4712b87eae576986422c4b8af4eb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73e38eaa0e8b27b0d9f6d5ecba1574bee9d6bcfe"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c0098b68131e572e2071d2878d1f8de12621f6a2897ceeb053cdabbcbac8d80d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93f688ab930eacbb2b77a138a0470f74b735c194"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "91af2cf6c9c2e7be7a3c1a3692764f6d729155fd5ff2422c3c16a541ce509f88"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce8388fbbab2d73d8daa53c90eb94aace5316d61"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "cd87a89a2a51227ecacdeed3bb9fcaf102f29a3945706d637060286ce0f1e846"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53bf0bb3be00bc884ef421a67c2713f2bf58f20c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "de8b0319ee936effd6cea1f9326d257b2be54f49105888a20fd9f33eb3d98585"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e8817892815c73dce264e8de0e98a4f8262260b"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "791a7421d0ec05e81449e18eee76e7a3183188ae68adcfac6461e198691f08dc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "748712321aeca1020cf074dbba388db085cfff52"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "70c7d0e92360ee7f72df8c78e10bac0535f8ee741cf37d1e7f0b6c7f4a0e7ad9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2ac0ae76075435f02846e9924ce8b44417eec7e"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "45945af88c1983d348edd49cdd36dc0ecac18a48c97139cb2c086c37e593b418"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00483af3a53497b4b166f221232c858f4c162410"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "702274c915e73eb8763f91104fb8f1ce2752bf01972c2151f3c961c089808c64"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "13593565b70dcfe4e9f3b0c95ed5dedaacb66c57"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7c9a1a45205139e797cf9a6d099e6ddcc5ac6d32f9756e4af5bd7ac451ed6b64"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea86a76cd532cc28f7b3ff5ac67fb82ddcebaba4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d6fa5ad82f6b034cf9cb7d1bd94b77d3d12e75d57260135d78a8421b6ebc68d9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c823a1a407faa3f2496867543165ef894e200090"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "855110617d2d3f9bdf2365d78854099e605be715ae579f19e2473b03ec87b6bc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0d778fbf981bb51ac86ec759a6abdd76747d200"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1e140fa4224b549266064f683d1a0c4ad1137f7cd43c1ce22f1db25f0942f96b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3cfb5aeaa81dd44afc68a127f227fd8b67c4a00"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c97ac2174b1193bb325e475d718ffa4bda92efc1ed7cca61c338398bb8696971"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "d6df88825e0032118c0399285f68765d95bdea2d"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6e268dfae55870edf55aab3bcbf2ccd137e75326e7af76065f8f83e0baed63b4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85e939074432331d73aa266c10773cf58a8440c1"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "522792fa78bbda49e127ab49f31c54225750bc12912bf948af2af4aaea9a9ca5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "520b76af3c5874cec20ed12541eb75b0da540e47"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c51971abd16e4ac38e0d88c257ce6a9a471e91c2b844224a6b71935b6201e261"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v15.0.0+1/SPIRV_LLVM_Translator.v15.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
