[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fa9c57e72f16d07519dda9f79eb6e919eb85b36"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7aef0c5d1006b7d97a48c652ab0e392a8c2b424da36b6c98a1202efdb3a4f9e8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b7fbe776bda8b93c7859433209b5dd29bc4fc7f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a77b927086e7d4e44ada1f5a42ee449d6b1924c9f533dfb0dd87f647cc134829"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "947bb11caa89b0af5183eae1c812102752cdf5f1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "a014e9394cae7dc1e616a6077c465fb99fe2d208bec53f8ec7ee330fdda49d76"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f95b3546f933006bf831aa10a3b2fb5785d919ad"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "134f8bac209c041984cee8a813d5f2db48e4730b566b8935ec8fac69588ab149"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c42fdb4552a98d863276dce45a28ff01ea0c81da"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1777cb4fb1fd40f82148857a45495c7445fd68b2186b7a57926d873e2fc67e0e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e13a19c242716981d9508932f646b6d99b67a58b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4e0ce9ea9ad2e5fabadc8dc4c846ca0c1d2c54a50a91ba7c0f48cfb16642b8ae"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a0bad79e87db4e44b2231d7eaeb4d8ce31463bf"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e39877bc9d554847063dd68461f64e3191f87fb9190f480a1386d9d7ff4a6502"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d0dd36a416c782ad4a3dd2f179f628ee902e4d5"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0bb1e9186ccd16c796576a424af953fe90298a7c509281ab79f7411f1fd11b3c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "feaf2ffec6a625d0ccda41c5427c616829f9f116"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "42d0b80d5e6ee944bb4c5d9c58aa56004d14f5dc9ccea7ef6a8b5db4fbed6a59"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84d7b4810729b62fd009ea47a4f7f675ac79e7d4"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "13edc6d055ee8024af35b2ba2d77592efca13a8493e8e16012a2e58ba806a27f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d14d96176687b261bdc9b9b37a8e2adf24330a45"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "7107407b95d2b6f4e54c483d872a90f294cb13fd74e6d00b71385bc2ae50c831"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "a0c52dd722ea9536d42120ed4d1d3068b93ccc2c"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "277a3ff3bad71b6063eb0da7eac44d6ffb0d768e48df147aae3bd216cf57c4f2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "89896739f8420475285260020020c14a35e9e718"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "97ab98977c511764c22f8488d38aabc41a7f69ea214b70193852aec9e5ddd717"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "d2e183362e2783f52b54d2986ad3abcc9a6099e7"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d0607cf69ed521478d1bce30f5ec63276f1f1b75c72c4d9b98834411b5de49e1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "8386ef29f90ef710a0de647770398ccdcdee5999"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "973ac94a1be0a6428d27e2917183a56b135fc544e6fec5b479380cab2e27b49c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a193b84c6a067032bd0919e795ad24310cc955aa"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "98599beae35e0e390ab359336e988b449e93eefa869ea35234ba7d681623056e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ecef0e13f2a4f3b39d33ee6ee060ef3fedbbef30"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "924a3285a8e4e501d1ee2a2cee1a2b6c9d94b828fc4283cd62fe354ec2f7546c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v23.1.1+0/SPIRV_LLVM_Translator.v23.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
