[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "f1bd49ba23b61e4db4bcca94cdc74aaa39615341"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "eeaff5155e32f90b6afe5c23119dd37ec54c82a5675eebd7a98ed829e5ccd1cf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f44ca4184f199f6db1de79d347faac12a83f5fd8"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "653b5e245443cfdcced4dd9cfff5af748492659e539487c15d9672157bba954d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8868de6de899629625e58ffeacdf9cd4fa821302"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "eb8e43cefb17c73e60705a77f21767053898ed9c1e07ee138e49a07b614164bf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f45279385571f20c815feabaf6ee98d6ff9cfb9a"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ec75405fc654f578122ff98aa644d0918e7e55db813562b0a43265344cc920d7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "821a86268c09241381e2cf8f5c923917e8635284"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "0f1bfb7f75a82d4a7bb969a5ec59e6904646aad052b61ecf78e0ea02d03cbbab"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbdbafa804a2eba0fc1d6a9eef8ad2206d0ee2a1"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3a7fa3d109d08cf0f5c0966bfdd8d2b6ef9dbd031de444888da1f7ca3ac11aab"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b984bd10046475db8d67cedd2b83ea4688a152ae"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b27ca5c14cc92700180fffaedd9151e4cb4581ae6d577154557b348fe84db65a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b21bc8d1d2d234deb4293ab0fce20dd36b60dd9e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b2eb5b165f40e2027a7610dafa8d85bf256fda431599158f34684ce73e6769f3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a299efbbcaa2a5520037989ff613f7579d414b74"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "de1d957710cc35f07a2db04547fc837ac8d793c9603f98ee55b7833bb05d216d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb6dca3307c3a0d27e28584cb135b8376fd4fa3b"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "599ff41868dd4795250a394164b2db572a169cae372a89826db391dbf385a2ff"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34c63cdbae67286a4427bdec37682346b25fa4c4"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ad8db846713398ef7bd03fc440126c5eb084ebb2beba17e09556f10d062c28fb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dca6490fff748b6a72ee31bdc035d1c4ee52aeb"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "50899578e369c7d900518edb65df975623e4b9b5f28d5d60255d004ea0c348e1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66769ff64b031b37b836270f8df80b4d3294da71"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e2bcb4f2762da4b6a8355721ba5c781a1159fa3bd84b096fc82da47873f75bae"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad0b66edd6c5800dfbc68896e1863251e8e64024"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "97bb57198596b3387dad7137afcd0526f2e87c064830d133ca80e16b678ba340"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e68bb2794b6db701893fdc10d2dceaeab14e76dc"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d873e760886a7976167ddb6a7fa44590b8e69a14fc37c6d4f2c904033533d488"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b21cd36df154771cd2e3b324f61fe0004e91b4bc"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "60a164e94d9dbff5cdcdb9f70fdbb32b9410dc714937b759f45e14cf8b2619ca"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bb2b70d4e6c60f34e3383726a9f88d2a241f478"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "520d3226ad79bfdf3ee1c4764ece4639bf8fe235fa481de62152a0128a827880"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4105be2feb4c35475fa73d65cb5efaf7c3d7960"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c10f5ffdbbf03014e6ade92ea03d07751f75cadf3693d587bcf2915c1c2ce9ed"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8edff4106a91027bf4c2e0c5a460ee84ae61a3f5"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "47317a7f01769f054389a6a733b81211df26b9626419fce885237c301de946ae"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13e60e03fa5e17ae14cb09bd6c4f3e5a00bd64df"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3cc64b610d112cd2e74aa2669c8acf82de7017635087a64880df1de15e971fe9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e66aefd9e75d5187d77143a276d3092979e4edc7"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "eb9d45e565e499efcbb05282c70c01b1e3e8669bdc2a4d7fe882d38f8cb91334"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "8565edd9ccab61a0af1de3af559ac613b549b412"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "35d1c43e497a8e8ab57370dac118efb4e91d1b336cb6d59da88ebfd5a8f1ffad"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f12a37a3e0ead007f97af0569028725693b8a117"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "45afe38ed563ae16320e68ebed78b775a36cfbae2cf75e4fd58258a360d7d353"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "065e244cccb84bdf0cb7242aa3f479658ddcdd64"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4e8b82752b7a00f29846dc9cfb6033dc3f5ddcbde932ada6ab09f7972b79a7e5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a09c07ca11f3452ec9788aa0d7a935e5764f7fd"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "1d9a4d3e321b049602dc333f5aeb187fdac385374ce4c49a21b62f76583d98a7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9ab3c73e7d25b8651bb1bcc552b5468aa7c5f2e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "aab28ee74fb5dbe411533e55d491733fb12a57876be5316223c765a25af2e8e3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "1625107d54ac481ba08c5a4fd08f290004f57146"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "e29fa3e0d4c5865304b1d13ba3d3afd62e00ac2906ba90b209e955ecb0484e6c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e0ea610bb818ada52df197772e4ca778b6b26fd"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "148e65a2c39bb1e3cf3bd14da4f9b5bbbb6982f8e97c8fc3e7c26d27e0acae76"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec08735a9248a81d123de84b904815e12e82d23a"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c3c826757b35544745f8e4393cbf7ff1aea4130159b522356989e5dc874b787a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v13.0.0+1/SPIRV_LLVM_Translator.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
