[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "78987ce266169c1819f7c9d1c1a181350e411e95"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "4d7617a063b4d29763448068aaf2bfe2a1fff4b421c219808377adf86380698f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d00491ffd1e4553bd5075cc7516bc4e32d4e9c2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ec391d516bf380aa90844e54080031ab935b7c872904b964293765d920e5afdd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db47375135ba157d6472192093105c516792767f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ced867a4882dd43fbfbafeb8dcdf6b5b4c714dad35adcab871fcb7dc7369db8d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "122b09f656f042671363a66a33c5d439c501778f"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "084ef2095ef1e375c0ae06fe392848a459d5f1555091eba41a792f5019507cf9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a7b416e5d57925f50903331b7b7ac2c5d03f89e"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "76745e001a3757eeffc2e72e50a73cbff923fa25076d250337a92b16421b2dfe"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "aarch64"
git-tree-sha1 = "ace47e2a2789fc09bb3dde2c2dcccbfe2d7070d0"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "40cf4d41992f2b44fce2d4ad34c5721a620e69ef22e1addf067b2629d48a12c6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3700852b71be54ac35c5725a89879cfed01ae3d8"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "819db343af1e451205c8f8df42a79fb3d20efcaced7864db2ab8fb0133848a95"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "530ba136f8ed4afbe2d44b517538a4220337848c"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "74ddad0a546b07d3e2dc227f67d2420b490b93a3a8a79b40d202ee8bb13b37eb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a7a08047a57cc24438291c40cd47baa87b2fe7b"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "bd8fc54133cd2e76ec92436d38908647db7253d329ec0c6f72375a0a1e2c845f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3acca0b4768c683bc2e2ce27b3c6f97bc9e9492d"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "d604680c2f85499ea80bf3f402875ae00a1013a24f614635d571e7cd4ab1ac45"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1b93e85a5878cc3dfd35f3d34294d7554cdd4b8"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "751e654ea3b1e55817c33cb7cac83aebafaa6a4cf81f026747c9db5ced848fc1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94e5006e7e4a0be0e532bc9d839366aa856cd740"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "74feb526be6e47f75419640ff55f50a0b373543520671efb85ded0645ec48280"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cc22b97f343533beb8e62f71704096324f6f64c"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f89455ade6f0d622498aedd05e8fa30d684d219896f775d766849ec3026db42b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc5a61cd7820ab234d1ae3257bca7e788b653690"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "5c7f30332cbf70f3e3b1c26192719c76faa7c043d83ca0b4a30cc8b2deaa66ce"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a58fa53f2887da0a2070938e9f799249a9d89d0"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "029dae73a70433415d421b8025ab9ef06eba0ada09315cd22c63d212e0a897cf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "843523721e035f00284953d679c3220899490ace"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b38e674c4049d444d6f938e6e091e5edf87b047f5bfe35c7693c5c0d02de1cb3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c2820ce533b88d74e0e6c048349e26f7e2c9d94"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "954b8f56f2ef844dd7ae74fb9f5c95dc4e8ffd8a378fc40cea509db046e387cb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61021c10850c2f6c540576206055639bb3bd6ac7"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "10f4f4fc0c27759bae0f8518f2165c21f09816bbc56b0fc69d4f239b349bfdac"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b95e4d502c1df1766b4d780a2f9dcbb906bad4c5"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "79a99187575b89550b92b453e363ad9986e92c7e190021995f972363c24c64ed"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7eb490ec35bc74714cfe717f2c9830a8226aae2"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f892ed9ef84261a4b97acfafe3803380a402011e38a5ee92fe0a5a83a4e8902e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7faddb3995b00263f98795231cbab270ed178d6f"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "aa20ae34648a0a3fb03a9b94152571dd83b39b3a4263112db10682058dee143e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6290803101b1edb0af3b01e8b3e1e9c597c49927"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "6be30c1799e031caf315ba4830461dd0de7b348fbc4daf6a24bea8e93764b927"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "e41e0bfc122635570c3c8df8549bb5873d3b6990"
os = "macos"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "c69e3660cd68b882e8abcf20ccc55dbec6d1a242931b7fbb06ba4d9cf1d8f45e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb048210c0bfabf5734b9b55f5cf81be42d525ea"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "82c47d31628311f83f4e63134695723b56cc250ea5aebbd63f4f6d44d875766d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a704fe9dae3b7e0dd38d15f57774a0799a618d8"
libc = "glibc"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "3cac66d34f384e0e522030179920a77dc6786fbae95cfe465be2b62e9ddae107"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "428e0443d54b08a3b08f773a9bf46ec3071f0b9d"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "ae4d793cd978785a94e7ef39abd1d4501d724285e604ed1e2f74e0274c221d56"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdae7777283a98e64e17fe3a006cdb37acfbaefa"
libc = "musl"
os = "linux"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "f19bd87c4a8a8267229f1ad688713e86ee40daf7287cd4ee52cde4371a5226d0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
git-tree-sha1 = "b8100c9225637c802c21cc38741cb043dbd4d23f"
os = "freebsd"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "89526b817a029b07cfdeb81ac738785ce27c617184f8d29c0d07d4c88197a7db"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20abdc1f49c996234acf7aac13044162ad0c35d6"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "77f27807ac55d11bad7f2d6576d78582dc997e82c3d6e5635f03b44d991a3a41"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_LLVM_Translator]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df48760445a71bb396ab735814d8505266c01ed0"
os = "windows"

    [[SPIRV_LLVM_Translator.download]]
    sha256 = "b63b96de7e52dc74dbe740c7984cd8dd8ea9490ac32344acf1cb235b435e162d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_LLVM_Translator_jll.jl/releases/download/SPIRV_LLVM_Translator-v19.1.0+0/SPIRV_LLVM_Translator.v19.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
