# Autogenerated wrapper script for SPIRV_LLVM_Translator_jll for aarch64-apple-darwin
export libllvm_spirv

using Zstd_jll
JLLWrappers.@generate_wrapper_header("SPIRV_LLVM_Translator")
JLLWrappers.@declare_library_product(libllvm_spirv, "@rpath/libllvm_spirv.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zstd_jll)
    JLLWrappers.@init_library_product(
        libllvm_spirv,
        "lib/libllvm_spirv.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
