# Autogenerated wrapper script for SPIRV_LLVM_Translator_jll for armv6l-linux-gnueabihf-cxx11
export libllvm_spirv

using Zstd_jll
JLLWrappers.@generate_wrapper_header("SPIRV_LLVM_Translator")
JLLWrappers.@declare_library_product(libllvm_spirv, "libllvm_spirv.so")
function __init__()
    JLLWrappers.@generate_init_header(Zstd_jll)
    JLLWrappers.@init_library_product(
        libllvm_spirv,
        "lib/libllvm_spirv.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
