# Autogenerated wrapper script for SPIRV_LLVM_Translator_jll for i686-w64-mingw32-cxx11
export libllvm_spirv

using Zstd_jll
JLLWrappers.@generate_wrapper_header("SPIRV_LLVM_Translator")
JLLWrappers.@declare_library_product(libllvm_spirv, "libllvm_spirv.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zstd_jll)
    JLLWrappers.@init_library_product(
        libllvm_spirv,
        "bin\\libllvm_spirv.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
