# Autogenerated wrapper script for SPIRV_LLVM_Translator_jll for x86_64-w64-mingw32-cxx03
export llvm_spirv

using Zstd_jll
JLLWrappers.@generate_wrapper_header("SPIRV_LLVM_Translator")
JLLWrappers.@declare_executable_product(llvm_spirv)
function __init__()
    JLLWrappers.@generate_init_header(Zstd_jll)
    JLLWrappers.@init_executable_product(
        llvm_spirv,
        "bin\\llvm-spirv.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
